knp_paginator:
    page_range: 5                    # Number of pages displayed in the pagination menu
    default_options:
        page_name: page              # Parameter name for the page number in the URL
        sort_field_name: sort        # Parameter name for the sorting field in the URL
        sort_direction_name: direction  # Parameter name for the sorting direction in the URL
        distinct: true               # Ensure distinct results, useful when paginating with joins