#index:
#    path: /
#    controller: App\Controller\DefaultController::index
get_images:
    path: '/get_images'
    controller: 'App\Controller\UserController::getImages'


base_admin:
    path: '/base-admin'
    controller: 'App\Controller\UserAuthController::baseAdmin'

base_client:
    path: '/base-client'
    controller: 'App\Controller\UserAuthController::baseClient'

base_designer:
    path: '/base-designer'
    controller: 'App\Controller\UserAuthController::baseDesigner'

search_users:
    path: /search-users
    controller: App\Controller\UserController::searchUsers